# Generated by Django 5.1.1 on 2024-11-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_detalleorden_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='precio_unitario',
            new_name='precio_final',
        ),
    ]
