# Generated by Django 5.1.1 on 2024-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
